import AppKit
import Observation

/// A table tab's three views, as in Postico: the rows, the definition, and the SQL behind it.
enum TablePane: String, CaseIterable, Identifiable {
    case content, structure, ddl

    var id: String { rawValue }

    var title: String {
        switch self {
        case .content: "Content"
        case .structure: "Structure"
        case .ddl: "DDL"
        }
    }
}

/// One column as it is in the database.
struct ColumnInfo: Equatable {
    let name: String
    /// `format_type` output, e.g. `character varying(50)`.
    let type: String
    let defaultValue: String?
    let notNull: Bool
    let comment: String?
    let isPrimaryKey: Bool
    /// `GENERATED ALWAYS AS IDENTITY` / `GENERATED BY DEFAULT AS IDENTITY`, or nil.
    let identity: String?
    /// The expression of a `GENERATED ALWAYS AS (…) STORED` column, or nil.
    let generated: String?
}

/// A column as the user is editing it. `original` is nil for a column being added.
struct ColumnDraft: Identifiable, Equatable {
    let id = UUID()
    let original: ColumnInfo?
    var name: String
    var type: String
    /// Default expression; empty means none.
    var defaultValue: String
    var notNull: Bool
    var comment: String
    var isDropped = false

    init(_ column: ColumnInfo) {
        original = column
        name = column.name
        type = column.type
        defaultValue = column.defaultValue ?? ""
        notNull = column.notNull
        comment = column.comment ?? ""
    }

    init(newNamed name: String) {
        original = nil
        self.name = name
        type = "text"
        defaultValue = ""
        notNull = false
        comment = ""
    }

    var isNew: Bool { original == nil }

    /// Identity and generated columns get their values from Postgres, so their default isn't editable.
    var hasManagedDefault: Bool { original?.identity != nil || original?.generated != nil }

    var isModified: Bool {
        guard let original else { return true }
        return isDropped || name != original.name || type != original.type
            || defaultValue != (original.defaultValue ?? "") || notNull != original.notNull
            || comment != (original.comment ?? "")
    }
}

struct IndexInfo: Equatable {
    let name: String
    /// `pg_get_indexdef` output: the full `CREATE INDEX` statement.
    let definition: String
    let columns: String
    let method: String
    let isUnique: Bool
    let isPrimary: Bool
    /// Set when the index backs a constraint (primary key, unique, exclusion); drop the constraint instead.
    let constraint: String?
}

/// An index the user is adding.
struct IndexDraft: Identifiable, Equatable {
    let id = UUID()
    var name: String
    var columns: [String]
    var isUnique: Bool
    var method: String

    var columnList: String { columns.map(quoteIdent).joined(separator: ", ") }
}

struct ConstraintInfo: Equatable {
    let name: String
    /// `p`, `u`, `f`, `c` or `x`.
    let type: String
    /// `pg_get_constraintdef` output, e.g. `FOREIGN KEY (user_id) REFERENCES users(id)`.
    let definition: String

    var typeName: String {
        switch type {
        case "p": "Primary key"
        case "u": "Unique"
        case "f": "Foreign key"
        case "c": "Check"
        case "x": "Exclusion"
        default: type
        }
    }
}

/// The Structure and DDL views of a table: loads the definition from the catalog, keeps the user's
/// edits as drafts, and turns them into ALTER statements that are saved together in one transaction.
@MainActor @Observable
final class TableStructureModel {
    let relation: RelationRef
    private let connection: PGConnection
    /// Called after a save that renamed the table, with its new reference.
    @ObservationIgnored var onRenamed: ((RelationRef) -> Void)?
    /// Called after any other save, so the content view picks up new or changed columns.
    @ObservationIgnored var onSaved: (() async -> Void)?

    private(set) var isLoaded = false
    private(set) var isLoading = false
    private(set) var isSaving = false
    var error: String?

    private(set) var columns: [ColumnInfo] = []
    private(set) var indexes: [IndexInfo] = []
    private(set) var constraints: [ConstraintInfo] = []
    private(set) var tableComment: String?
    /// `CREATE VIEW … AS` body for views and materialized views.
    private(set) var viewDefinition: String?
    private(set) var triggers: [String] = []

    // Drafts
    var draftName = ""
    var draftComment = ""
    var columnDrafts: [ColumnDraft] = []
    var newIndexes: [IndexDraft] = []
    private(set) var droppedIndexes: Set<String> = []
    private(set) var droppedConstraints: Set<String> = []

    init(relation: RelationRef, connection: PGConnection) {
        self.relation = relation
        self.connection = connection
    }

    var isEditable: Bool { relation.kind == .table }

    // MARK: Loading

    func start() async {
        guard !isLoaded, !isLoading else { return }
        await load()
    }

    func load() async {
        isLoading = true
        defer { isLoading = false }
        let oid = [relation.qualifiedName]

        let columnSQL = """
            SELECT a.attname,
                   format_type(a.atttypid, a.atttypmod),
                   pg_get_expr(d.adbin, d.adrelid),
                   a.attnotnull,
                   col_description(a.attrelid, a.attnum),
                   EXISTS (SELECT 1 FROM pg_index i WHERE i.indrelid = a.attrelid AND i.indisprimary
                           AND a.attnum = ANY(i.indkey)),
                   a.attidentity,
                   a.attgenerated
            FROM pg_attribute a
            LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
            WHERE a.attrelid = $1::regclass AND a.attnum > 0 AND NOT a.attisdropped
            ORDER BY a.attnum
            """
        let indexSQL = """
            SELECT ic.relname,
                   pg_get_indexdef(i.indexrelid),
                   am.amname,
                   i.indisunique,
                   i.indisprimary,
                   con.conname,
                   (SELECT string_agg(pg_get_indexdef(i.indexrelid, k, true), ', ' ORDER BY k)
                      FROM generate_series(1, i.indnkeyatts) k)
            FROM pg_index i
            JOIN pg_class ic ON ic.oid = i.indexrelid
            JOIN pg_am am ON am.oid = ic.relam
            LEFT JOIN pg_constraint con ON con.conindid = i.indexrelid AND con.conrelid = i.indrelid
            WHERE i.indrelid = $1::regclass
            ORDER BY i.indisprimary DESC, ic.relname
            """
        let constraintSQL = """
            SELECT conname, contype, pg_get_constraintdef(oid, true)
            FROM pg_constraint
            WHERE conrelid = $1::regclass
            ORDER BY CASE contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 ELSE 3 END, conname
            """
        let tableSQL = """
            SELECT obj_description($1::regclass, 'pg_class'),
                   CASE WHEN c.relkind IN ('v', 'm') THEN pg_get_viewdef($1::regclass, true) END
            FROM pg_class c WHERE c.oid = $1::regclass
            """
        let triggerSQL = """
            SELECT pg_get_triggerdef(oid, true) FROM pg_trigger
            WHERE tgrelid = $1::regclass AND NOT tgisinternal ORDER BY tgname
            """

        let columnOutcome = await connection.execute(columnSQL, params: oid)
        if let message = columnOutcome.error {
            error = message
            return
        }
        let rows = columnOutcome.results.first?.rows
        columns = (0..<(rows?.rowCount ?? 0)).compactMap { row in
            guard let rows, let name = rows.value(row: row, column: 0), let type = rows.value(row: row, column: 1)
            else { return nil }
            let identity: String? = switch rows.value(row: row, column: 6) {
            case "a": "GENERATED ALWAYS AS IDENTITY"
            case "d": "GENERATED BY DEFAULT AS IDENTITY"
            default: nil
            }
            let isGenerated = rows.value(row: row, column: 7) == "s"
            let expression = rows.value(row: row, column: 2)
            return ColumnInfo(
                name: name, type: type,
                defaultValue: isGenerated ? nil : expression,
                notNull: rows.value(row: row, column: 3) == "t",
                comment: rows.value(row: row, column: 4),
                isPrimaryKey: rows.value(row: row, column: 5) == "t",
                identity: identity,
                generated: isGenerated ? expression : nil
            )
        }

        if let rows = await connection.execute(indexSQL, params: oid).results.first?.rows {
            indexes = (0..<rows.rowCount).compactMap { row in
                guard let name = rows.value(row: row, column: 0), let definition = rows.value(row: row, column: 1)
                else { return nil }
                return IndexInfo(
                    name: name, definition: definition,
                    columns: rows.value(row: row, column: 6) ?? "",
                    method: rows.value(row: row, column: 2) ?? "btree",
                    isUnique: rows.value(row: row, column: 3) == "t",
                    isPrimary: rows.value(row: row, column: 4) == "t",
                    constraint: rows.value(row: row, column: 5)
                )
            }
        }
        if let rows = await connection.execute(constraintSQL, params: oid).results.first?.rows {
            constraints = (0..<rows.rowCount).compactMap { row in
                guard let name = rows.value(row: row, column: 0), let type = rows.value(row: row, column: 1),
                      let definition = rows.value(row: row, column: 2)
                else { return nil }
                return ConstraintInfo(name: name, type: type, definition: definition)
            }
        }
        if let rows = await connection.execute(tableSQL, params: oid).results.first?.rows {
            tableComment = rows.value(row: 0, column: 0)
            viewDefinition = rows.value(row: 0, column: 1)
        }
        if let rows = await connection.execute(triggerSQL, params: oid).results.first?.rows {
            triggers = (0..<rows.rowCount).compactMap { rows.value(row: $0, column: 0) }
        }

        resetDrafts()
        error = nil
        isLoaded = true
    }

    private func resetDrafts() {
        draftName = relation.name
        draftComment = tableComment ?? ""
        columnDrafts = columns.map(ColumnDraft.init)
        newIndexes = []
        droppedIndexes = []
        droppedConstraints = []
    }

    // MARK: Editing

    func addColumn() {
        let existing = Set(columnDrafts.map(\.name))
        var name = "new_column"
        var number = 2
        while existing.contains(name) {
            name = "new_column_\(number)"
            number += 1
        }
        columnDrafts.append(ColumnDraft(newNamed: name))
    }

    /// New columns disappear; existing ones are marked and can be restored until saved.
    func toggleDrop(_ id: ColumnDraft.ID) {
        guard let index = columnDrafts.firstIndex(where: { $0.id == id }) else { return }
        if columnDrafts[index].isNew {
            columnDrafts.remove(at: index)
        } else {
            columnDrafts[index].isDropped.toggle()
        }
    }

    func revertColumn(_ id: ColumnDraft.ID) {
        guard let index = columnDrafts.firstIndex(where: { $0.id == id }),
              let original = columnDrafts[index].original else { return }
        columnDrafts[index] = ColumnDraft(original)
    }

    /// A free index name like `orders_customer_id_idx`.
    func suggestedIndexName(columns: [String]) -> String {
        let taken = Set(indexes.map(\.name) + newIndexes.map(\.name))
        let base = String(([relation.name] + columns + ["idx"]).joined(separator: "_").prefix(60))
        var name = base
        var number = 2
        while taken.contains(name) {
            name = "\(base)\(number)"
            number += 1
        }
        return name
    }

    func addIndex(_ index: IndexDraft) {
        newIndexes.append(index)
    }

    func removeNewIndex(_ id: IndexDraft.ID) {
        newIndexes.removeAll { $0.id == id }
    }

    func toggleDropIndex(_ name: String) {
        if droppedIndexes.contains(name) { droppedIndexes.remove(name) } else { droppedIndexes.insert(name) }
    }

    func toggleDropConstraint(_ name: String) {
        if droppedConstraints.contains(name) { droppedConstraints.remove(name) } else { droppedConstraints.insert(name) }
    }

    func discardChanges() {
        resetDrafts()
        error = nil
    }

    // MARK: Pending changes

    var trimmedDraftName: String { draftName.trimmingCharacters(in: .whitespacesAndNewlines) }

    /// The ALTER / CREATE / DROP / COMMENT statements that apply the drafts, in a safe order: drops first,
    /// then column changes, additions and new indexes, and the table rename last so everything before
    /// it can use the current name.
    var pendingStatements: [String] {
        guard isEditable, isLoaded else { return [] }
        let table = relation.qualifiedName
        var statements: [String] = []

        for name in droppedConstraints.sorted() {
            statements.append("ALTER TABLE \(table) DROP CONSTRAINT \(quoteIdent(name))")
        }
        for name in droppedIndexes.sorted() {
            statements.append("DROP INDEX \(quoteIdent(relation.schema)).\(quoteIdent(name))")
        }
        for draft in columnDrafts where draft.isDropped {
            if let original = draft.original {
                statements.append("ALTER TABLE \(table) DROP COLUMN \(quoteIdent(original.name))")
            }
        }

        for draft in columnDrafts where !draft.isDropped {
            let name = draft.name.trimmingCharacters(in: .whitespaces)
            let type = draft.type.trimmingCharacters(in: .whitespaces)
            let defaultValue = draft.defaultValue.trimmingCharacters(in: .whitespaces)
            guard let original = draft.original else {
                var definition = "ALTER TABLE \(table) ADD COLUMN \(quoteIdent(name)) \(type)"
                if !defaultValue.isEmpty { definition += " DEFAULT \(defaultValue)" }
                if draft.notNull { definition += " NOT NULL" }
                statements.append(definition)
                if !draft.comment.isEmpty {
                    statements.append("COMMENT ON COLUMN \(table).\(quoteIdent(name)) IS \(quoteLiteral(draft.comment))")
                }
                continue
            }
            let column = quoteIdent(name)
            if name != original.name {
                statements.append("ALTER TABLE \(table) RENAME COLUMN \(quoteIdent(original.name)) TO \(column)")
            }
            if type != original.type {
                statements.append("ALTER TABLE \(table) ALTER COLUMN \(column) TYPE \(type) USING \(column)::\(type)")
            }
            if !draft.hasManagedDefault, defaultValue != (original.defaultValue ?? "") {
                statements.append(defaultValue.isEmpty
                    ? "ALTER TABLE \(table) ALTER COLUMN \(column) DROP DEFAULT"
                    : "ALTER TABLE \(table) ALTER COLUMN \(column) SET DEFAULT \(defaultValue)")
            }
            if draft.notNull != original.notNull {
                statements.append("ALTER TABLE \(table) ALTER COLUMN \(column) \(draft.notNull ? "SET" : "DROP") NOT NULL")
            }
            if draft.comment != (original.comment ?? "") {
                statements.append("COMMENT ON COLUMN \(table).\(column) IS "
                    + (draft.comment.isEmpty ? "NULL" : quoteLiteral(draft.comment)))
            }
        }

        for index in newIndexes {
            statements.append("CREATE \(index.isUnique ? "UNIQUE " : "")INDEX \(quoteIdent(index.name)) ON \(table)"
                + (index.method == "btree" ? "" : " USING \(index.method)") + " (\(index.columnList))")
        }

        if draftComment != (tableComment ?? "") {
            statements.append("COMMENT ON TABLE \(table) IS " + (draftComment.isEmpty ? "NULL" : quoteLiteral(draftComment)))
        }
        if !trimmedDraftName.isEmpty, trimmedDraftName != relation.name {
            statements.append("ALTER TABLE \(table) RENAME TO \(quoteIdent(trimmedDraftName))")
        }
        return statements
    }

    var hasPendingChanges: Bool { !pendingStatements.isEmpty }

    var pendingSummary: String {
        let count = pendingStatements.count
        return count == 1 ? "1 change" : "\(count) changes"
    }

    /// Something that would make the save fail before it reaches the server.
    var validationError: String? {
        if trimmedDraftName.isEmpty { return "The table needs a name" }
        let names = columnDrafts.filter { !$0.isDropped }.map { $0.name.trimmingCharacters(in: .whitespaces) }
        if names.contains(where: \.isEmpty) { return "Every column needs a name" }
        if Set(names).count != names.count { return "Two columns have the same name" }
        if columnDrafts.contains(where: { !$0.isDropped && $0.type.trimmingCharacters(in: .whitespaces).isEmpty }) {
            return "Every column needs a type"
        }
        return nil
    }

    var pendingPreview: String {
        pendingStatements.map { $0 + ";" }.joined(separator: "\n")
    }

    /// Runs every pending statement in one transaction: all of it applies, or none of it.
    func save() async {
        let statements = pendingStatements
        guard !statements.isEmpty, !isSaving else { return }
        if let validationError {
            error = validationError
            return
        }
        isSaving = true
        defer { isSaving = false }
        let outcome = await connection.executeInTransaction(statements.map { ($0, []) }, commit: true)
        if let message = outcome.error {
            error = message  // rolled back; the drafts stay so the user can fix them
            return
        }
        error = nil
        let newName = trimmedDraftName
        if newName != relation.name {
            onRenamed?(RelationRef(schema: relation.schema, name: newName, kind: relation.kind))
            return
        }
        await load()
        await onSaved?()
    }

    // MARK: DDL

    /// SQL that recreates the table or view, written like Postico: `public.` left out and identifiers
    /// only quoted where needed.
    var ddl: String {
        guard isLoaded else { return "" }
        let name = displayName(schema: relation.schema, name: relation.name)
        var parts: [String] = []

        switch relation.kind {
        case .view, .materializedView:
            let keyword = relation.kind == .view ? "VIEW" : "MATERIALIZED VIEW"
            let body = (viewDefinition ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
            parts.append("CREATE \(keyword) \(name) AS\n\(body.hasSuffix(";") ? String(body.dropLast()) : body);")
        case .table, .foreignTable:
            var lines = columns.map { column -> String in
                var line = "    \(displayIdent(column.name)) \(column.type)"
                if let generated = column.generated { line += " GENERATED ALWAYS AS (\(generated)) STORED" }
                if let identity = column.identity { line += " \(identity)" }
                if let defaultValue = column.defaultValue, column.identity == nil { line += " DEFAULT \(defaultValue)" }
                if column.notNull { line += " NOT NULL" }
                return line
            }
            lines += constraints.map { "    CONSTRAINT \(displayIdent($0.name)) \($0.definition)" }
            parts.append("CREATE TABLE \(name) (\n\(lines.joined(separator: ",\n"))\n);")
        }

        // Constraint-backed indexes are already covered by the CONSTRAINT lines above.
        let plainIndexes = indexes.filter { $0.constraint == nil }
        if !plainIndexes.isEmpty {
            parts.append(plainIndexes.map { simplified($0.definition) + ";" }.joined(separator: "\n"))
        }
        if !triggers.isEmpty {
            parts.append(triggers.map { simplified($0) + ";" }.joined(separator: "\n"))
        }

        var comments: [String] = []
        let kindKeyword = switch relation.kind {
        case .table: "TABLE"
        case .view: "VIEW"
        case .materializedView: "MATERIALIZED VIEW"
        case .foreignTable: "FOREIGN TABLE"
        }
        if let tableComment { comments.append("COMMENT ON \(kindKeyword) \(name) IS \(quoteLiteral(tableComment));") }
        for column in columns {
            if let comment = column.comment {
                comments.append("COMMENT ON COLUMN \(name).\(displayIdent(column.name)) IS \(quoteLiteral(comment));")
            }
        }
        if !comments.isEmpty { parts.append(comments.joined(separator: "\n")) }

        if hasPendingChanges {
            parts.append("-- Pending changes, not saved yet:\n" + pendingPreview)
        }
        return parts.joined(separator: "\n\n") + "\n"
    }

    @ObservationIgnored private var highlightCache: (ddl: String, text: AttributedString)?

    /// The DDL with the editor's syntax colors. Highlighting is the slow part, so it's only redone
    /// when the SQL changes, not on every redraw.
    var highlightedDDL: AttributedString {
        let ddl = ddl
        if let cache = highlightCache, cache.ddl == ddl { return cache.text }
        // The storage's own font wins over a SwiftUI .font, so start it in the editor's monospaced font.
        let storage = NSTextStorage(string: ddl, attributes: [.font: SQLHighlighter.font])
        SQLHighlighter.highlight(storage)
        let text = (try? AttributedString(storage, including: \.appKit)) ?? AttributedString(ddl)
        highlightCache = (ddl, text)
        return text
    }

    private func displayName(schema: String, name: String) -> String {
        schema == "public" ? displayIdent(name) : "\(displayIdent(schema)).\(displayIdent(name))"
    }

    /// `pg_get_indexdef` and friends always qualify with `public.`; drop it for readability.
    private func simplified(_ definition: String) -> String {
        definition.replacingOccurrences(of: " ON public.", with: " ON ")
    }
}

/// Quotes an identifier only when Postgres needs it, for SQL shown to people.
func displayIdent(_ identifier: String) -> String {
    let isPlain = identifier.first.map { $0 == "_" || ($0.isLetter && $0.isLowercase && $0.isASCII) } == true
        && identifier.allSatisfy { $0 == "_" || $0.isNumber || ($0.isLetter && $0.isLowercase && $0.isASCII) }
    return isPlain && !SQLKeywords.reserved.contains(identifier) ? identifier : quoteIdent(identifier)
}

/// A SQL string literal.
func quoteLiteral(_ value: String) -> String {
    "'" + value.replacingOccurrences(of: "'", with: "''") + "'"
}

enum SQLKeywords {
    /// Reserved words that must be quoted as identifiers.
    static let reserved: Set<String> = [
        "all", "analyse", "analyze", "and", "any", "array", "as", "asc", "asymmetric", "both", "case", "cast",
        "check", "collate", "column", "constraint", "create", "current_catalog", "current_date", "current_role",
        "current_time", "current_timestamp", "current_user", "default", "deferrable", "desc", "distinct", "do",
        "else", "end", "except", "false", "fetch", "for", "foreign", "from", "grant", "group", "having", "in",
        "initially", "intersect", "into", "lateral", "leading", "limit", "localtime", "localtimestamp", "not",
        "null", "offset", "on", "only", "or", "order", "placing", "primary", "references", "returning", "select",
        "session_user", "some", "symmetric", "table", "then", "to", "trailing", "true", "union", "unique", "user",
        "using", "variadic", "when", "where", "window", "with",
    ]
}
